apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
spec:
  selector:
  # labels are used as selectors 
    project: roboshop
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 # container port